<h1>ACCORDION</h1>
    <div class="content-country">
            <div class="level-0">
                <h2 class="ecommerce">
                    <span>EUROPE</span>
                </h2>
                    <div class="level-1">
                        <h4><span>FRANCE</span></h4>
                        <ul>
                            <li>
                                <p>
                                    <a href="#">test</a>
                                    <span class="arrival"><strong>A</strong></span>
                                    <span class="departure"><strong>D</strong></span>
                                </p>
                            </li>
                        </ul>
                    </div>
                <h2 class="ecommerce">
                    <span>NORTH-AMERICA</span>
                </h2>
                    <div class="level-1">
                        <h4><span>FRANCE</span></h4>
                        <ul>
                            <li>
                                <p>
                                    <a href="#">test</a>
                                        <span class="arrival"><strong>A</strong></span>
                                        <span class="departure"><strong>D</strong></span>
                                </p>
                            </li>
                            <li>
                                <p>
                                    <a href="#">test</a>
                                    <span class="arrival"><strong>A</strong></span>
                                    <span class="departure"><strong>D</strong></span>
                                </p>
                            </li>
                            <li>
                                <p>
                                    <a href="#">test</a>
                                    <span class="arrival"><strong>A</strong></span>
                                    <span class="departure"><strong>D</strong></span>
                                </p>
                            </li>
                        </ul>
                    </div>
                    <div class="level-1">
                        <h4><span>FRANCE</span></h4>
                        <ul>
                            <li>
                                <p>
                                    <a href="#">test</a>
                                    <span class="arrival"><strong>A</strong></span>
                                    <span class="departure"><strong>D</strong></span>
                                </p>
                            </li>
                            <li>
                                <p>
                                    <a href="#">test</a>
                                    <span class="arrival"><strong>A</strong></span>
                                    <span class="departure"><strong>D</strong></span>
                                </p>
                            </li>
                            <li>
                                <p>
                                    <a href="#">test</a>
                                    <span class="arrival"><strong>A</strong></span>
                                    <span class="departure"><strong>D</strong></span>
                                </p>
                            </li>
                        </ul>
                    </div>
            </div>
    </div>